language: php
php:
  - "hhvm"
  - "hhvm-nightly"
before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
script:
  - composer test
sudo: false
